# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Firebase-Crashlytics-Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firebase-Crashlytics-Sample

pod 'Fabric', '~> 1.10.2'
pod 'Crashlytics', '~> 3.13.4'
pod 'Firebase/Analytics'

end
